name: Test
on:
  push:
    branches:
      - main
    paths-ignore:
      - '**/*.md'
      - LICENSE
      - '**/*.gitignore'
      - .editorconfig
      - docs/**
  pull_request:

jobs:
  test_node:
    name: "Test node@${{ matrix.node }}"
    runs-on: ubuntu-latest
    permissions:
      contents: read
    strategy:
      fail-fast: true
      matrix:
        node:
          - '20'
          - '22'
          - '24'
          - '26'
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: Install Node.JS
        uses: actions/setup-node@v6
        with:
          cache: 'yarn'
          node-version: ${{ matrix.node }}

      - name: Install Javascript dependencies
        run: yarn install --immutable

      - name: Run linters
        run: yarn lint

      - name: Run tests
        run: yarn test

  test_bun:
    name: "Test bun@${{ matrix.bun }}"
    runs-on: ubuntu-latest
    permissions:
      contents: read
    strategy:
      fail-fast: true
      matrix:
        bun:
          - '1.x'
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: ${{ matrix.bun }}

      - name: Install Javascript dependencies
        run: bun install

      - name: Run tests
        run: bun test

  test_deno:
    name: "Test deno@${{ matrix.deno }}"
    runs-on: ubuntu-latest
    permissions:
      contents: read
    strategy:
      fail-fast: true
      matrix:
        deno:
          - 'v2.x'
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: ${{ matrix.deno }}

      - name: Install Javascript dependencies
        run: deno install --node-modules-dir=auto

      - name: Run tests
        run: deno task test

  test_browsers:
    name: "Test browsers"
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.59.1
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: Install Node.JS
        uses: actions/setup-node@v6
        with:
          cache: 'yarn'
          node-version-file: '.tool-versions'

      - name: Install dependencies
        run: yarn install --immutable

      - name: Run tests in browsers
        run: yarn test:browser
